name: final_login
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  auto_route: ^7.8.4
  get_it: ^7.6.7
  auto_route_generator: ^7.3.2
  shared_preferences: ^2.2.2
  salomon_bottom_bar: ^3.3.2
  material_color_utilities: ^0.8.0
  animated_notch_bottom_bar: ^1.0.2
  curved_navigation_bar: ^1.0.3
  toggle_switch: ^2.3.0
  flutter_barcode_scanner: ^2.0.0
  line_awesome_flutter: ^2.0.0
  get: ^4.6.6
  sleek_circular_slider: ^2.0.1
  url_strategy: ^0.2.0
  flutter_launcher_icons: ^0.13.1
  intl: ^0.19.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/image/

  # Adding flutter_localizations as part of the Flutter SDK
  generate: true
